title: Dockizy Documentation
img: "/img/dockizy.png" # logo of the documentation
background_color: "#0D83CD" # color of background on hover
text_color: "#000" #color of the text on hover
description:  >-
   Dockizy é um tema simples, fácil e rápido para criar documentações.<br><a href="https://github.com/felipegs07/dockizy" target="_blank" rel="noopener">Conheça</a>